credentials:
  usernames:
    akash:
      email: sathishakash2003@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: akash
      password: abc # Will be hashed automatically
    aparna:
      email: aparnaarun2k02@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: aparna
      password: aparna@2024 # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
  - melsby@gmail.com